# Generated by Django 5.1.2 on 2025-01-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id_fuel', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del combustible')),
                ('name_fuel', models.CharField(max_length=200, verbose_name='Nombre del combustible')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('expiration_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad disponible')),
            ],
            options={
                'verbose_name': 'Combustible',
                'verbose_name_plural': 'Combustibles',
            },
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id_pesticide', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del pesticida')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del pesticida')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('unit_of_measurement', models.CharField(max_length=50, verbose_name='Unidad de medida')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('expiration_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad disponible')),
            ],
            options={
                'verbose_name': 'Pesticida',
                'verbose_name_plural': 'Pesticidas',
            },
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad ingresada')),
                ('quantity_out', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad retirada')),
                ('transaction_date', models.DateField(auto_now_add=True, verbose_name='Fecha de transacción')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.fuel', verbose_name='Combustible')),
            ],
            options={
                'verbose_name': 'Transacción de Combustible',
                'verbose_name_plural': 'Transacciones de Combustibles',
            },
        ),
        migrations.CreateModel(
            name='PesticideTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad ingresada')),
                ('quantity_out', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantidad retirada')),
                ('transaction_date', models.DateField(auto_now_add=True, verbose_name='Fecha de transacción')),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.pesticide', verbose_name='Pesticida')),
            ],
            options={
                'verbose_name': 'Transacción de Pesticida',
                'verbose_name_plural': 'Transacciones de Pesticidas',
            },
        ),
    ]
