# Generated by Django 5.1.5 on 2025-01-27 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id_fuel', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('unit_of_measurement', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('supplier', models.CharField(max_length=200)),
                ('fuel_type', models.CharField(default='', max_length=100)),
                ('presentation', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id_pesticide', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('unit_of_measurement', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('presentation', models.CharField(max_length=100)),
                ('active_principle', models.CharField(max_length=100)),
                ('concentration', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id_seed', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('seed_type', models.CharField(max_length=255)),
                ('presentation', models.CharField(max_length=255)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id_fuel_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_in', models.PositiveIntegerField(default=0)),
                ('quantity_out', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fuel')),
            ],
        ),
        migrations.CreateModel(
            name='PesticideTransaction',
            fields=[
                ('id_pesticide_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_in', models.PositiveIntegerField(default=0)),
                ('quantity_out', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pesticide')),
            ],
        ),
        migrations.CreateModel(
            name='SeedTransaction',
            fields=[
                ('id_seed_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_in', models.PositiveIntegerField(default=0)),
                ('quantity_out', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.seed')),
            ],
        ),
    ]
