# Generated by Django 5.1.5 on 2025-01-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='forma_de_presentacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma de presentación'),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='forma_de_presentacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma de presentación'),
        ),
    ]
