# Generated by Django 5.1.5 on 2025-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidetransaction',
            name='created_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
