# Generated by Django 5.1.5 on 2025-04-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='seed',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
