# Generated by Django 5.1.5 on 2025-04-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_fuel_observations_pesticide_observations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuel',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='observations',
        ),
        migrations.AddField(
            model_name='fueltransaction',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesticidetransaction',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedtransaction',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
