# Generated by Django 5.1.5 on 2025-01-21 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_fuel_forma_de_presentacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuel',
            options={'verbose_name': 'Fuel', 'verbose_name_plural': 'Fuels'},
        ),
        migrations.AlterModelOptions(
            name='fueltransaction',
            options={'verbose_name': 'Fuel Transaction', 'verbose_name_plural': 'Fuel Transactions'},
        ),
        migrations.AlterModelOptions(
            name='pesticide',
            options={'verbose_name': 'Pesticide', 'verbose_name_plural': 'Pesticides'},
        ),
        migrations.AlterModelOptions(
            name='pesticidetransaction',
            options={'verbose_name': 'Pesticide Transaction', 'verbose_name_plural': 'Pesticide Transactions'},
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='forma_de_presentacion',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='forma_de_presentacion',
        ),
        migrations.AddField(
            model_name='fuel',
            name='presentation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Presentation'),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='presentation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Presentation'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Available Quantity'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='expiration_date',
            field=models.DateField(verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='id_fuel',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Fuel ID'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='name_fuel',
            field=models.CharField(max_length=200, verbose_name='Fuel Name'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.fuel', verbose_name='Fuel'),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='quantity_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity In'),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='quantity_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity Out'),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='transaction_date',
            field=models.DateField(auto_now_add=True, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Available Quantity'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='expiration_date',
            field=models.DateField(verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='id_pesticide',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Pesticide ID'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Pesticide Name'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='unit_of_measurement',
            field=models.CharField(max_length=50, verbose_name='Unit of Measurement'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='pesticidetransaction',
            name='pesticide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.pesticide', verbose_name='Pesticide'),
        ),
        migrations.AlterField(
            model_name='pesticidetransaction',
            name='quantity_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity In'),
        ),
        migrations.AlterField(
            model_name='pesticidetransaction',
            name='quantity_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity Out'),
        ),
        migrations.AlterField(
            model_name='pesticidetransaction',
            name='transaction_date',
            field=models.DateField(auto_now_add=True, verbose_name='Transaction Date'),
        ),
    ]
