# Generated by Django 5.1.2 on 2025-05-14 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_fuel_observations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='quantity_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='quantity_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='transaction_value',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12000),
        ),
        migrations.AlterField(
            model_name='fueltransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pesticidetransaction',
            name='quantity_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pesticidetransaction',
            name='quantity_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pesticidetransaction',
            name='transaction_value',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12000),
        ),
        migrations.AlterField(
            model_name='pesticidetransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='seed',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='seedtransaction',
            name='quantity_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='seedtransaction',
            name='quantity_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='seedtransaction',
            name='transaction_value',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12000),
        ),
        migrations.AlterField(
            model_name='seedtransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
